import Navbar from "@/components/Navbar"
import Providers from "@/components/Providers"
import { Inter } from 'next/font/google'

import { cn } from "@/lib/utils"
import "@/styles/globals.css"
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
const inter = Inter({ subsets: ['latin'] })

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={cn(inter.className)}>
      <body className="bg-slate-50 text-slate-900 dark:text-slate-50 dark:bg-slate-900 antialiased">
        <Providers>
          <Navbar/>
          {children}
        </Providers>
      </body>
    </html>
  )
}

